import {
  FaRegEnvelope,
  FaTwitter,
  FaGithub,
  FaFacebookF,
  FaYoutube,
  FaInstagram,
  FaLinkedinIn,
  FaBehance,
  FaBitbucket,
  FaCodepen,
  FaDiscord,
  FaDribbble,
  Fa500Px,
  FaEtsy,
  FaFlickr,
  FaGitlab,
  FaLastfm,
  FaMediumM,
  FaPatreon,
  FaPaypal,
  FaPinterestP,
  FaRedditAlien,
  FaSlack,
  FaSnapchatGhost,
  FaSoundcloud,
  FaSpotify,
  FaStackOverflow,
  FaTumblr,
  FaWeibo,
  FaVimeoV,
  FaYelp,
  FaQq,
  FaWhatsapp,
  FaShare,
} from "react-icons/fa"

export default {
  default: FaShare,
  email: FaRegEnvelope,
  twitter: FaTwitter,
  github: FaGithub,
  facebook: FaFacebookF,
  youtube: FaYoutube,
  instagram: FaInstagram,
  linkedin: FaLinkedinIn,
  behance: FaBehance,
  bitbucket: FaBitbucket,
  codepen: FaCodepen,
  discord: FaDiscord,
  dribble: FaDribbble,
  "500px": Fa500Px,
  etsy: FaEtsy,
  flickr: FaFlickr,
  gitlab: FaGitlab,
  lastfm: FaLastfm,
  medium: FaMediumM,
  patreon: FaPatreon,
  paypal: FaPaypal,
  pinterest: FaPinterestP,
  reddit: FaRedditAlien,
  slack: FaSlack,
  snapchat: FaSnapchatGhost,
  soundcloud: FaSoundcloud,
  spotify: FaSpotify,
  stackoverflow: FaStackOverflow,
  tumblr: FaTumblr,
  weibo: FaWeibo,
  vimeo: FaVimeoV,
  yelp: FaYelp,
  qq: FaQq,
  whatsapp: FaWhatsapp,
}
